[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "robot-logger"
version = "1.0.0"
description = "Robot working hours logger"
dependencies = ["pytz", "fpdf2"]

[project.scripts]
logger-install = "logger_system.install_service:install_service"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
logger_system = ["*.sh", "*.py", "*.service"]
